namespace Tfg_NetFramework
{
    partial class reminderList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(reminderList));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.dgvReminder = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.idRecordatorio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.titulo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.recordatorio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.fecha = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.hora = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tbReminderTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbReminderReminder = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbReminderDate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbReminderHour = new Bunifu.UI.WinForms.BunifuTextBox();
            this.blbReminderTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.blbReminderReminder = new Bunifu.UI.WinForms.BunifuLabel();
            this.blbReminderDate = new Bunifu.UI.WinForms.BunifuLabel();
            this.blbReminderHour = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnReminderRemove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnReminderAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnUpdateDgvReminder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDgvReminderUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.dgvReminder)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvReminder
            // 
            this.dgvReminder.AllowCustomTheming = false;
            this.dgvReminder.AllowUserToAddRows = false;
            this.dgvReminder.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvReminder.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvReminder.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvReminder.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvReminder.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvReminder.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvReminder.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvReminder.ColumnHeadersHeight = 40;
            this.dgvReminder.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.idRecordatorio,
            this.titulo,
            this.recordatorio,
            this.fecha,
            this.hora});
            this.dgvReminder.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvReminder.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvReminder.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvReminder.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvReminder.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvReminder.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvReminder.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvReminder.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvReminder.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvReminder.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvReminder.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvReminder.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvReminder.CurrentTheme.Name = null;
            this.dgvReminder.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvReminder.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvReminder.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvReminder.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvReminder.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvReminder.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvReminder.EnableHeadersVisualStyles = false;
            this.dgvReminder.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvReminder.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvReminder.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvReminder.HeaderForeColor = System.Drawing.Color.White;
            this.dgvReminder.Location = new System.Drawing.Point(29, 28);
            this.dgvReminder.Name = "dgvReminder";
            this.dgvReminder.RowHeadersVisible = false;
            this.dgvReminder.RowHeadersWidth = 51;
            this.dgvReminder.RowTemplate.Height = 40;
            this.dgvReminder.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvReminder.Size = new System.Drawing.Size(461, 571);
            this.dgvReminder.TabIndex = 0;
            this.dgvReminder.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvReminder.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvReminder_CellClick);
            // 
            // idRecordatorio
            // 
            this.idRecordatorio.HeaderText = "Id del Recordatorio";
            this.idRecordatorio.MinimumWidth = 6;
            this.idRecordatorio.Name = "idRecordatorio";
            // 
            // titulo
            // 
            this.titulo.HeaderText = "Título";
            this.titulo.MinimumWidth = 6;
            this.titulo.Name = "titulo";
            // 
            // recordatorio
            // 
            this.recordatorio.HeaderText = "Recordatorio";
            this.recordatorio.MinimumWidth = 6;
            this.recordatorio.Name = "recordatorio";
            // 
            // fecha
            // 
            this.fecha.HeaderText = "Fecha";
            this.fecha.MinimumWidth = 6;
            this.fecha.Name = "fecha";
            // 
            // hora
            // 
            this.hora.HeaderText = "Hora";
            this.hora.MinimumWidth = 6;
            this.hora.Name = "hora";
            // 
            // tbReminderTitle
            // 
            this.tbReminderTitle.AcceptsReturn = false;
            this.tbReminderTitle.AcceptsTab = false;
            this.tbReminderTitle.AnimationSpeed = 200;
            this.tbReminderTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbReminderTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbReminderTitle.AutoSizeHeight = true;
            this.tbReminderTitle.BackColor = System.Drawing.Color.Transparent;
            this.tbReminderTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbReminderTitle.BackgroundImage")));
            this.tbReminderTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbReminderTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbReminderTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbReminderTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbReminderTitle.BorderRadius = 10;
            this.tbReminderTitle.BorderThickness = 1;
            this.tbReminderTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbReminderTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbReminderTitle.DefaultText = "";
            this.tbReminderTitle.FillColor = System.Drawing.Color.White;
            this.tbReminderTitle.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            this.tbReminderTitle.HideSelection = true;
            this.tbReminderTitle.IconLeft = null;
            this.tbReminderTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderTitle.IconPadding = 3;
            this.tbReminderTitle.IconRight = null;
            this.tbReminderTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderTitle.Lines = new string[0];
            this.tbReminderTitle.Location = new System.Drawing.Point(508, 70);
            this.tbReminderTitle.MaxLength = 32767;
            this.tbReminderTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbReminderTitle.Modified = false;
            this.tbReminderTitle.Multiline = false;
            this.tbReminderTitle.Name = "tbReminderTitle";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderTitle.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbReminderTitle.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderTitle.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderTitle.OnIdleState = stateProperties4;
            this.tbReminderTitle.Padding = new System.Windows.Forms.Padding(3);
            this.tbReminderTitle.PasswordChar = '\0';
            this.tbReminderTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbReminderTitle.PlaceholderText = "Enter text";
            this.tbReminderTitle.ReadOnly = false;
            this.tbReminderTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbReminderTitle.SelectedText = "";
            this.tbReminderTitle.SelectionLength = 0;
            this.tbReminderTitle.SelectionStart = 0;
            this.tbReminderTitle.ShortcutsEnabled = true;
            this.tbReminderTitle.Size = new System.Drawing.Size(314, 34);
            this.tbReminderTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbReminderTitle.TabIndex = 99;
            this.tbReminderTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbReminderTitle.TextMarginBottom = 0;
            this.tbReminderTitle.TextMarginLeft = 3;
            this.tbReminderTitle.TextMarginTop = 1;
            this.tbReminderTitle.TextPlaceholder = "Enter text";
            this.tbReminderTitle.UseSystemPasswordChar = false;
            this.tbReminderTitle.WordWrap = true;
            // 
            // tbReminderReminder
            // 
            this.tbReminderReminder.AcceptsReturn = false;
            this.tbReminderReminder.AcceptsTab = false;
            this.tbReminderReminder.AnimationSpeed = 200;
            this.tbReminderReminder.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbReminderReminder.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbReminderReminder.AutoSizeHeight = true;
            this.tbReminderReminder.BackColor = System.Drawing.Color.Transparent;
            this.tbReminderReminder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbReminderReminder.BackgroundImage")));
            this.tbReminderReminder.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbReminderReminder.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbReminderReminder.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbReminderReminder.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbReminderReminder.BorderRadius = 10;
            this.tbReminderReminder.BorderThickness = 1;
            this.tbReminderReminder.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbReminderReminder.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderReminder.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbReminderReminder.DefaultText = "";
            this.tbReminderReminder.FillColor = System.Drawing.Color.White;
            this.tbReminderReminder.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            this.tbReminderReminder.HideSelection = true;
            this.tbReminderReminder.IconLeft = null;
            this.tbReminderReminder.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderReminder.IconPadding = 3;
            this.tbReminderReminder.IconRight = null;
            this.tbReminderReminder.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderReminder.Lines = new string[0];
            this.tbReminderReminder.Location = new System.Drawing.Point(508, 235);
            this.tbReminderReminder.MaxLength = 32767;
            this.tbReminderReminder.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbReminderReminder.Modified = false;
            this.tbReminderReminder.Multiline = true;
            this.tbReminderReminder.Name = "tbReminderReminder";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderReminder.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbReminderReminder.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderReminder.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderReminder.OnIdleState = stateProperties8;
            this.tbReminderReminder.Padding = new System.Windows.Forms.Padding(3);
            this.tbReminderReminder.PasswordChar = '\0';
            this.tbReminderReminder.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbReminderReminder.PlaceholderText = "Enter text";
            this.tbReminderReminder.ReadOnly = false;
            this.tbReminderReminder.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbReminderReminder.SelectedText = "";
            this.tbReminderReminder.SelectionLength = 0;
            this.tbReminderReminder.SelectionStart = 0;
            this.tbReminderReminder.ShortcutsEnabled = true;
            this.tbReminderReminder.Size = new System.Drawing.Size(314, 156);
            this.tbReminderReminder.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbReminderReminder.TabIndex = 100;
            this.tbReminderReminder.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbReminderReminder.TextMarginBottom = 0;
            this.tbReminderReminder.TextMarginLeft = 3;
            this.tbReminderReminder.TextMarginTop = 1;
            this.tbReminderReminder.TextPlaceholder = "Enter text";
            this.tbReminderReminder.UseSystemPasswordChar = false;
            this.tbReminderReminder.WordWrap = true;
            // 
            // tbReminderDate
            // 
            this.tbReminderDate.AcceptsReturn = false;
            this.tbReminderDate.AcceptsTab = false;
            this.tbReminderDate.AnimationSpeed = 200;
            this.tbReminderDate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbReminderDate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbReminderDate.AutoSizeHeight = true;
            this.tbReminderDate.BackColor = System.Drawing.Color.Transparent;
            this.tbReminderDate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbReminderDate.BackgroundImage")));
            this.tbReminderDate.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbReminderDate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbReminderDate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbReminderDate.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbReminderDate.BorderRadius = 10;
            this.tbReminderDate.BorderThickness = 1;
            this.tbReminderDate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbReminderDate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderDate.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbReminderDate.DefaultText = "";
            this.tbReminderDate.FillColor = System.Drawing.Color.White;
            this.tbReminderDate.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            this.tbReminderDate.HideSelection = true;
            this.tbReminderDate.IconLeft = null;
            this.tbReminderDate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderDate.IconPadding = 3;
            this.tbReminderDate.IconRight = null;
            this.tbReminderDate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderDate.Lines = new string[0];
            this.tbReminderDate.Location = new System.Drawing.Point(508, 152);
            this.tbReminderDate.MaxLength = 32767;
            this.tbReminderDate.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbReminderDate.Modified = false;
            this.tbReminderDate.Multiline = false;
            this.tbReminderDate.Name = "tbReminderDate";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderDate.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbReminderDate.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderDate.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderDate.OnIdleState = stateProperties12;
            this.tbReminderDate.Padding = new System.Windows.Forms.Padding(3);
            this.tbReminderDate.PasswordChar = '\0';
            this.tbReminderDate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbReminderDate.PlaceholderText = "Enter text";
            this.tbReminderDate.ReadOnly = false;
            this.tbReminderDate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbReminderDate.SelectedText = "";
            this.tbReminderDate.SelectionLength = 0;
            this.tbReminderDate.SelectionStart = 0;
            this.tbReminderDate.ShortcutsEnabled = true;
            this.tbReminderDate.Size = new System.Drawing.Size(144, 34);
            this.tbReminderDate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbReminderDate.TabIndex = 101;
            this.tbReminderDate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbReminderDate.TextMarginBottom = 0;
            this.tbReminderDate.TextMarginLeft = 3;
            this.tbReminderDate.TextMarginTop = 1;
            this.tbReminderDate.TextPlaceholder = "Enter text";
            this.tbReminderDate.UseSystemPasswordChar = false;
            this.tbReminderDate.WordWrap = true;
            // 
            // tbReminderHour
            // 
            this.tbReminderHour.AcceptsReturn = false;
            this.tbReminderHour.AcceptsTab = false;
            this.tbReminderHour.AnimationSpeed = 200;
            this.tbReminderHour.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbReminderHour.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbReminderHour.AutoSizeHeight = true;
            this.tbReminderHour.BackColor = System.Drawing.Color.Transparent;
            this.tbReminderHour.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbReminderHour.BackgroundImage")));
            this.tbReminderHour.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbReminderHour.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbReminderHour.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbReminderHour.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbReminderHour.BorderRadius = 10;
            this.tbReminderHour.BorderThickness = 1;
            this.tbReminderHour.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbReminderHour.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderHour.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbReminderHour.DefaultText = "";
            this.tbReminderHour.FillColor = System.Drawing.Color.White;
            this.tbReminderHour.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            this.tbReminderHour.HideSelection = true;
            this.tbReminderHour.IconLeft = null;
            this.tbReminderHour.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderHour.IconPadding = 3;
            this.tbReminderHour.IconRight = null;
            this.tbReminderHour.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbReminderHour.Lines = new string[0];
            this.tbReminderHour.Location = new System.Drawing.Point(686, 152);
            this.tbReminderHour.MaxLength = 32767;
            this.tbReminderHour.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbReminderHour.Modified = false;
            this.tbReminderHour.Multiline = false;
            this.tbReminderHour.Name = "tbReminderHour";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderHour.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbReminderHour.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderHour.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbReminderHour.OnIdleState = stateProperties16;
            this.tbReminderHour.Padding = new System.Windows.Forms.Padding(3);
            this.tbReminderHour.PasswordChar = '\0';
            this.tbReminderHour.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbReminderHour.PlaceholderText = "Enter text";
            this.tbReminderHour.ReadOnly = false;
            this.tbReminderHour.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbReminderHour.SelectedText = "";
            this.tbReminderHour.SelectionLength = 0;
            this.tbReminderHour.SelectionStart = 0;
            this.tbReminderHour.ShortcutsEnabled = true;
            this.tbReminderHour.Size = new System.Drawing.Size(144, 34);
            this.tbReminderHour.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbReminderHour.TabIndex = 102;
            this.tbReminderHour.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbReminderHour.TextMarginBottom = 0;
            this.tbReminderHour.TextMarginLeft = 3;
            this.tbReminderHour.TextMarginTop = 1;
            this.tbReminderHour.TextPlaceholder = "Enter text";
            this.tbReminderHour.UseSystemPasswordChar = false;
            this.tbReminderHour.WordWrap = true;
            // 
            // blbReminderTitle
            // 
            this.blbReminderTitle.AllowParentOverrides = false;
            this.blbReminderTitle.AutoEllipsis = false;
            this.blbReminderTitle.AutoSize = false;
            this.blbReminderTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.blbReminderTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.blbReminderTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.blbReminderTitle.Location = new System.Drawing.Point(508, 28);
            this.blbReminderTitle.Name = "blbReminderTitle";
            this.blbReminderTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.blbReminderTitle.Size = new System.Drawing.Size(144, 36);
            this.blbReminderTitle.TabIndex = 103;
            this.blbReminderTitle.Text = "<h3>Título*</h3>";
            this.blbReminderTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.blbReminderTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // blbReminderReminder
            // 
            this.blbReminderReminder.AllowParentOverrides = false;
            this.blbReminderReminder.AutoEllipsis = false;
            this.blbReminderReminder.AutoSize = false;
            this.blbReminderReminder.CursorType = null;
            this.blbReminderReminder.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.blbReminderReminder.Location = new System.Drawing.Point(508, 192);
            this.blbReminderReminder.Name = "blbReminderReminder";
            this.blbReminderReminder.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.blbReminderReminder.Size = new System.Drawing.Size(118, 39);
            this.blbReminderReminder.TabIndex = 104;
            this.blbReminderReminder.Text = "<h3>Recordatorio</h3>";
            this.blbReminderReminder.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.blbReminderReminder.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // blbReminderDate
            // 
            this.blbReminderDate.AllowParentOverrides = false;
            this.blbReminderDate.AutoEllipsis = false;
            this.blbReminderDate.AutoSize = false;
            this.blbReminderDate.CursorType = null;
            this.blbReminderDate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.blbReminderDate.Location = new System.Drawing.Point(508, 110);
            this.blbReminderDate.Name = "blbReminderDate";
            this.blbReminderDate.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.blbReminderDate.Size = new System.Drawing.Size(118, 41);
            this.blbReminderDate.TabIndex = 105;
            this.blbReminderDate.Text = "<h3>Fecha*</h3>";
            this.blbReminderDate.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.blbReminderDate.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // blbReminderHour
            // 
            this.blbReminderHour.AllowParentOverrides = false;
            this.blbReminderHour.AutoEllipsis = false;
            this.blbReminderHour.AutoSize = false;
            this.blbReminderHour.CursorType = null;
            this.blbReminderHour.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.blbReminderHour.Location = new System.Drawing.Point(686, 109);
            this.blbReminderHour.Name = "blbReminderHour";
            this.blbReminderHour.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.blbReminderHour.Size = new System.Drawing.Size(110, 42);
            this.blbReminderHour.TabIndex = 106;
            this.blbReminderHour.Text = "<h3>Hora</h3>";
            this.blbReminderHour.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.blbReminderHour.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.Crimson;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClose.ButtonText = "Close";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges1;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btnClose.IdleBorderRadius = 10;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.Crimson;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(604, 592);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 10;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.BorderRadius = 10;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnClose.OnIdleState.BorderRadius = 10;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.BorderRadius = 10;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(95, 39);
            this.btnClose.TabIndex = 107;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnReminderRemove
            // 
            this.btnReminderRemove.AllowAnimations = true;
            this.btnReminderRemove.AllowMouseEffects = true;
            this.btnReminderRemove.AllowToggling = false;
            this.btnReminderRemove.AnimationSpeed = 200;
            this.btnReminderRemove.AutoGenerateColors = false;
            this.btnReminderRemove.AutoRoundBorders = false;
            this.btnReminderRemove.AutoSizeLeftIcon = true;
            this.btnReminderRemove.AutoSizeRightIcon = true;
            this.btnReminderRemove.BackColor = System.Drawing.Color.Transparent;
            this.btnReminderRemove.BackColor1 = System.Drawing.Color.Crimson;
            this.btnReminderRemove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReminderRemove.BackgroundImage")));
            this.btnReminderRemove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderRemove.ButtonText = "Eliminar Recordatorio";
            this.btnReminderRemove.ButtonTextMarginLeft = 0;
            this.btnReminderRemove.ColorContrastOnClick = 45;
            this.btnReminderRemove.ColorContrastOnHover = 45;
            this.btnReminderRemove.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnReminderRemove.CustomizableEdges = borderEdges2;
            this.btnReminderRemove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReminderRemove.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReminderRemove.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReminderRemove.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReminderRemove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReminderRemove.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnReminderRemove.ForeColor = System.Drawing.Color.White;
            this.btnReminderRemove.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReminderRemove.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReminderRemove.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReminderRemove.IconMarginLeft = 11;
            this.btnReminderRemove.IconPadding = 10;
            this.btnReminderRemove.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReminderRemove.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReminderRemove.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReminderRemove.IconSize = 25;
            this.btnReminderRemove.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btnReminderRemove.IdleBorderRadius = 10;
            this.btnReminderRemove.IdleBorderThickness = 1;
            this.btnReminderRemove.IdleFillColor = System.Drawing.Color.Crimson;
            this.btnReminderRemove.IdleIconLeftImage = null;
            this.btnReminderRemove.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnReminderRemove.IdleIconRightImage")));
            this.btnReminderRemove.IndicateFocus = false;
            this.btnReminderRemove.Location = new System.Drawing.Point(562, 502);
            this.btnReminderRemove.Name = "btnReminderRemove";
            this.btnReminderRemove.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReminderRemove.OnDisabledState.BorderRadius = 10;
            this.btnReminderRemove.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderRemove.OnDisabledState.BorderThickness = 1;
            this.btnReminderRemove.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReminderRemove.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReminderRemove.OnDisabledState.IconLeftImage = null;
            this.btnReminderRemove.OnDisabledState.IconRightImage = null;
            this.btnReminderRemove.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReminderRemove.onHoverState.BorderRadius = 10;
            this.btnReminderRemove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderRemove.onHoverState.BorderThickness = 1;
            this.btnReminderRemove.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReminderRemove.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnReminderRemove.onHoverState.IconLeftImage = null;
            this.btnReminderRemove.onHoverState.IconRightImage = null;
            this.btnReminderRemove.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnReminderRemove.OnIdleState.BorderRadius = 10;
            this.btnReminderRemove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderRemove.OnIdleState.BorderThickness = 1;
            this.btnReminderRemove.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnReminderRemove.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReminderRemove.OnIdleState.IconLeftImage = null;
            this.btnReminderRemove.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("btnReminderRemove.OnIdleState.IconRightImage")));
            this.btnReminderRemove.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReminderRemove.OnPressedState.BorderRadius = 10;
            this.btnReminderRemove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderRemove.OnPressedState.BorderThickness = 1;
            this.btnReminderRemove.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReminderRemove.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReminderRemove.OnPressedState.IconLeftImage = null;
            this.btnReminderRemove.OnPressedState.IconRightImage = null;
            this.btnReminderRemove.Size = new System.Drawing.Size(194, 39);
            this.btnReminderRemove.TabIndex = 109;
            this.btnReminderRemove.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReminderRemove.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReminderRemove.TextMarginLeft = 0;
            this.btnReminderRemove.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnReminderRemove.UseDefaultRadiusAndThickness = true;
            this.btnReminderRemove.Click += new System.EventHandler(this.btnReminderRemove_Click);
            // 
            // btnReminderAdd
            // 
            this.btnReminderAdd.AllowAnimations = true;
            this.btnReminderAdd.AllowMouseEffects = true;
            this.btnReminderAdd.AllowToggling = false;
            this.btnReminderAdd.AnimationSpeed = 200;
            this.btnReminderAdd.AutoGenerateColors = false;
            this.btnReminderAdd.AutoRoundBorders = false;
            this.btnReminderAdd.AutoSizeLeftIcon = true;
            this.btnReminderAdd.AutoSizeRightIcon = true;
            this.btnReminderAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnReminderAdd.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btnReminderAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReminderAdd.BackgroundImage")));
            this.btnReminderAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderAdd.ButtonText = "Añadir Recordatorio";
            this.btnReminderAdd.ButtonTextMarginLeft = 0;
            this.btnReminderAdd.ColorContrastOnClick = 45;
            this.btnReminderAdd.ColorContrastOnHover = 45;
            this.btnReminderAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnReminderAdd.CustomizableEdges = borderEdges3;
            this.btnReminderAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReminderAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReminderAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReminderAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReminderAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReminderAdd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnReminderAdd.ForeColor = System.Drawing.Color.White;
            this.btnReminderAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReminderAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReminderAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReminderAdd.IconMarginLeft = 11;
            this.btnReminderAdd.IconPadding = 10;
            this.btnReminderAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReminderAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReminderAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReminderAdd.IconSize = 25;
            this.btnReminderAdd.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.btnReminderAdd.IdleBorderRadius = 10;
            this.btnReminderAdd.IdleBorderThickness = 1;
            this.btnReminderAdd.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnReminderAdd.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReminderAdd.IdleIconLeftImage")));
            this.btnReminderAdd.IdleIconRightImage = null;
            this.btnReminderAdd.IndicateFocus = false;
            this.btnReminderAdd.Location = new System.Drawing.Point(562, 457);
            this.btnReminderAdd.Name = "btnReminderAdd";
            this.btnReminderAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReminderAdd.OnDisabledState.BorderRadius = 10;
            this.btnReminderAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderAdd.OnDisabledState.BorderThickness = 1;
            this.btnReminderAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReminderAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReminderAdd.OnDisabledState.IconLeftImage = null;
            this.btnReminderAdd.OnDisabledState.IconRightImage = null;
            this.btnReminderAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReminderAdd.onHoverState.BorderRadius = 10;
            this.btnReminderAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderAdd.onHoverState.BorderThickness = 1;
            this.btnReminderAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnReminderAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnReminderAdd.onHoverState.IconLeftImage = null;
            this.btnReminderAdd.onHoverState.IconRightImage = null;
            this.btnReminderAdd.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.btnReminderAdd.OnIdleState.BorderRadius = 10;
            this.btnReminderAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderAdd.OnIdleState.BorderThickness = 1;
            this.btnReminderAdd.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btnReminderAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReminderAdd.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReminderAdd.OnIdleState.IconLeftImage")));
            this.btnReminderAdd.OnIdleState.IconRightImage = null;
            this.btnReminderAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReminderAdd.OnPressedState.BorderRadius = 10;
            this.btnReminderAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReminderAdd.OnPressedState.BorderThickness = 1;
            this.btnReminderAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnReminderAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReminderAdd.OnPressedState.IconLeftImage = null;
            this.btnReminderAdd.OnPressedState.IconRightImage = null;
            this.btnReminderAdd.Size = new System.Drawing.Size(194, 39);
            this.btnReminderAdd.TabIndex = 108;
            this.btnReminderAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReminderAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReminderAdd.TextMarginLeft = 0;
            this.btnReminderAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnReminderAdd.UseDefaultRadiusAndThickness = true;
            this.btnReminderAdd.Click += new System.EventHandler(this.btnReminderAdd_Click);
            // 
            // btnUpdateDgvReminder
            // 
            this.btnUpdateDgvReminder.AllowAnimations = true;
            this.btnUpdateDgvReminder.AllowMouseEffects = true;
            this.btnUpdateDgvReminder.AllowToggling = false;
            this.btnUpdateDgvReminder.AnimationSpeed = 200;
            this.btnUpdateDgvReminder.AutoGenerateColors = false;
            this.btnUpdateDgvReminder.AutoRoundBorders = false;
            this.btnUpdateDgvReminder.AutoSizeLeftIcon = true;
            this.btnUpdateDgvReminder.AutoSizeRightIcon = true;
            this.btnUpdateDgvReminder.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdateDgvReminder.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btnUpdateDgvReminder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdateDgvReminder.BackgroundImage")));
            this.btnUpdateDgvReminder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateDgvReminder.ButtonText = "Actualizar recordatorio";
            this.btnUpdateDgvReminder.ButtonTextMarginLeft = 0;
            this.btnUpdateDgvReminder.ColorContrastOnClick = 45;
            this.btnUpdateDgvReminder.ColorContrastOnHover = 45;
            this.btnUpdateDgvReminder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnUpdateDgvReminder.CustomizableEdges = borderEdges4;
            this.btnUpdateDgvReminder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdateDgvReminder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdateDgvReminder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdateDgvReminder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdateDgvReminder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnUpdateDgvReminder.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnUpdateDgvReminder.ForeColor = System.Drawing.Color.White;
            this.btnUpdateDgvReminder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdateDgvReminder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdateDgvReminder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpdateDgvReminder.IconMarginLeft = 11;
            this.btnUpdateDgvReminder.IconPadding = 10;
            this.btnUpdateDgvReminder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdateDgvReminder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdateDgvReminder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdateDgvReminder.IconSize = 25;
            this.btnUpdateDgvReminder.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdateDgvReminder.IdleBorderRadius = 10;
            this.btnUpdateDgvReminder.IdleBorderThickness = 1;
            this.btnUpdateDgvReminder.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdateDgvReminder.IdleIconLeftImage = null;
            this.btnUpdateDgvReminder.IdleIconRightImage = null;
            this.btnUpdateDgvReminder.IndicateFocus = false;
            this.btnUpdateDgvReminder.Location = new System.Drawing.Point(562, 412);
            this.btnUpdateDgvReminder.Name = "btnUpdateDgvReminder";
            this.btnUpdateDgvReminder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdateDgvReminder.OnDisabledState.BorderRadius = 10;
            this.btnUpdateDgvReminder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateDgvReminder.OnDisabledState.BorderThickness = 1;
            this.btnUpdateDgvReminder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdateDgvReminder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdateDgvReminder.OnDisabledState.IconLeftImage = null;
            this.btnUpdateDgvReminder.OnDisabledState.IconRightImage = null;
            this.btnUpdateDgvReminder.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdateDgvReminder.onHoverState.BorderRadius = 10;
            this.btnUpdateDgvReminder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateDgvReminder.onHoverState.BorderThickness = 1;
            this.btnUpdateDgvReminder.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdateDgvReminder.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUpdateDgvReminder.onHoverState.IconLeftImage = null;
            this.btnUpdateDgvReminder.onHoverState.IconRightImage = null;
            this.btnUpdateDgvReminder.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdateDgvReminder.OnIdleState.BorderRadius = 10;
            this.btnUpdateDgvReminder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateDgvReminder.OnIdleState.BorderThickness = 1;
            this.btnUpdateDgvReminder.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdateDgvReminder.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdateDgvReminder.OnIdleState.IconLeftImage = null;
            this.btnUpdateDgvReminder.OnIdleState.IconRightImage = null;
            this.btnUpdateDgvReminder.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdateDgvReminder.OnPressedState.BorderRadius = 10;
            this.btnUpdateDgvReminder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateDgvReminder.OnPressedState.BorderThickness = 1;
            this.btnUpdateDgvReminder.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdateDgvReminder.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdateDgvReminder.OnPressedState.IconLeftImage = null;
            this.btnUpdateDgvReminder.OnPressedState.IconRightImage = null;
            this.btnUpdateDgvReminder.Size = new System.Drawing.Size(194, 39);
            this.btnUpdateDgvReminder.TabIndex = 110;
            this.btnUpdateDgvReminder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdateDgvReminder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdateDgvReminder.TextMarginLeft = 0;
            this.btnUpdateDgvReminder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdateDgvReminder.UseDefaultRadiusAndThickness = true;
            this.btnUpdateDgvReminder.Click += new System.EventHandler(this.btnUpdateDgvReminder_Click);
            // 
            // btnDgvReminderUpdate
            // 
            this.btnDgvReminderUpdate.AllowAnimations = true;
            this.btnDgvReminderUpdate.AllowMouseEffects = true;
            this.btnDgvReminderUpdate.AllowToggling = false;
            this.btnDgvReminderUpdate.AnimationSpeed = 200;
            this.btnDgvReminderUpdate.AutoGenerateColors = false;
            this.btnDgvReminderUpdate.AutoRoundBorders = false;
            this.btnDgvReminderUpdate.AutoSizeLeftIcon = true;
            this.btnDgvReminderUpdate.AutoSizeRightIcon = true;
            this.btnDgvReminderUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnDgvReminderUpdate.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btnDgvReminderUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDgvReminderUpdate.BackgroundImage")));
            this.btnDgvReminderUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDgvReminderUpdate.ButtonText = "Actualizar recordatorios";
            this.btnDgvReminderUpdate.ButtonTextMarginLeft = 0;
            this.btnDgvReminderUpdate.ColorContrastOnClick = 45;
            this.btnDgvReminderUpdate.ColorContrastOnHover = 45;
            this.btnDgvReminderUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDgvReminderUpdate.CustomizableEdges = borderEdges5;
            this.btnDgvReminderUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDgvReminderUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDgvReminderUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDgvReminderUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDgvReminderUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDgvReminderUpdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDgvReminderUpdate.ForeColor = System.Drawing.Color.White;
            this.btnDgvReminderUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDgvReminderUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDgvReminderUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDgvReminderUpdate.IconMarginLeft = 11;
            this.btnDgvReminderUpdate.IconPadding = 10;
            this.btnDgvReminderUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDgvReminderUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDgvReminderUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDgvReminderUpdate.IconSize = 25;
            this.btnDgvReminderUpdate.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.btnDgvReminderUpdate.IdleBorderRadius = 10;
            this.btnDgvReminderUpdate.IdleBorderThickness = 1;
            this.btnDgvReminderUpdate.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnDgvReminderUpdate.IdleIconLeftImage = null;
            this.btnDgvReminderUpdate.IdleIconRightImage = null;
            this.btnDgvReminderUpdate.IndicateFocus = false;
            this.btnDgvReminderUpdate.Location = new System.Drawing.Point(562, 547);
            this.btnDgvReminderUpdate.Name = "btnDgvReminderUpdate";
            this.btnDgvReminderUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDgvReminderUpdate.OnDisabledState.BorderRadius = 10;
            this.btnDgvReminderUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDgvReminderUpdate.OnDisabledState.BorderThickness = 1;
            this.btnDgvReminderUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDgvReminderUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDgvReminderUpdate.OnDisabledState.IconLeftImage = null;
            this.btnDgvReminderUpdate.OnDisabledState.IconRightImage = null;
            this.btnDgvReminderUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDgvReminderUpdate.onHoverState.BorderRadius = 10;
            this.btnDgvReminderUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDgvReminderUpdate.onHoverState.BorderThickness = 1;
            this.btnDgvReminderUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDgvReminderUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDgvReminderUpdate.onHoverState.IconLeftImage = null;
            this.btnDgvReminderUpdate.onHoverState.IconRightImage = null;
            this.btnDgvReminderUpdate.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.btnDgvReminderUpdate.OnIdleState.BorderRadius = 10;
            this.btnDgvReminderUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDgvReminderUpdate.OnIdleState.BorderThickness = 1;
            this.btnDgvReminderUpdate.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btnDgvReminderUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDgvReminderUpdate.OnIdleState.IconLeftImage = null;
            this.btnDgvReminderUpdate.OnIdleState.IconRightImage = null;
            this.btnDgvReminderUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDgvReminderUpdate.OnPressedState.BorderRadius = 10;
            this.btnDgvReminderUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDgvReminderUpdate.OnPressedState.BorderThickness = 1;
            this.btnDgvReminderUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDgvReminderUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDgvReminderUpdate.OnPressedState.IconLeftImage = null;
            this.btnDgvReminderUpdate.OnPressedState.IconRightImage = null;
            this.btnDgvReminderUpdate.Size = new System.Drawing.Size(194, 39);
            this.btnDgvReminderUpdate.TabIndex = 111;
            this.btnDgvReminderUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDgvReminderUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDgvReminderUpdate.TextMarginLeft = 0;
            this.btnDgvReminderUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDgvReminderUpdate.UseDefaultRadiusAndThickness = true;
            this.btnDgvReminderUpdate.Click += new System.EventHandler(this.btnDgvReminderUpdate_Click);
            // 
            // reminderList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(850, 654);
            this.Controls.Add(this.btnDgvReminderUpdate);
            this.Controls.Add(this.btnUpdateDgvReminder);
            this.Controls.Add(this.btnReminderRemove);
            this.Controls.Add(this.btnReminderAdd);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.blbReminderHour);
            this.Controls.Add(this.blbReminderDate);
            this.Controls.Add(this.blbReminderReminder);
            this.Controls.Add(this.blbReminderTitle);
            this.Controls.Add(this.tbReminderHour);
            this.Controls.Add(this.tbReminderDate);
            this.Controls.Add(this.tbReminderReminder);
            this.Controls.Add(this.tbReminderTitle);
            this.Controls.Add(this.dgvReminder);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "reminderList";
            this.Text = "reminderList";
            this.Load += new System.EventHandler(this.reminderList_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvReminder)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dgvReminder;
        private System.Windows.Forms.DataGridViewTextBoxColumn idRecordatorio;
        private System.Windows.Forms.DataGridViewTextBoxColumn titulo;
        private System.Windows.Forms.DataGridViewTextBoxColumn recordatorio;
        private System.Windows.Forms.DataGridViewTextBoxColumn fecha;
        private System.Windows.Forms.DataGridViewTextBoxColumn hora;
        private Bunifu.UI.WinForms.BunifuTextBox tbReminderTitle;
        private Bunifu.UI.WinForms.BunifuTextBox tbReminderReminder;
        private Bunifu.UI.WinForms.BunifuTextBox tbReminderDate;
        private Bunifu.UI.WinForms.BunifuTextBox tbReminderHour;
        private Bunifu.UI.WinForms.BunifuLabel blbReminderTitle;
        private Bunifu.UI.WinForms.BunifuLabel blbReminderReminder;
        private Bunifu.UI.WinForms.BunifuLabel blbReminderDate;
        private Bunifu.UI.WinForms.BunifuLabel blbReminderHour;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReminderRemove;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReminderAdd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdateDgvReminder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDgvReminderUpdate;
    }
}